version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: yarn install
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run: set
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Install up
          command: curl -sf https://up.apex.sh/install | BINDIR=. sh
      - run:
          name: Deploy staging via up
          command: ./up deploy staging

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
